import type { Component } from 'vue'
import type { IconName } from './icons'

export type ToolCategory = 'Formatters' | 'Generators' | 'Converters' | 'Productivity'
export type ToolLoader = () => Promise<Component | { default: Component }>
export interface ToolDefinition { id: string; path: string; name: string; shortName: string; description: string; category: ToolCategory; icon: IconName; keywords: string[]; loader: ToolLoader }
export const toolCategories: ToolCategory[] = ['Formatters', 'Generators', 'Converters', 'Productivity']
export const categoryLabels: Record<ToolCategory, string> = { Formatters: 'Formatters', Generators: 'Generators', Converters: 'Converters', Productivity: 'To Do' }
export const tools: ToolDefinition[] = [
  { id: 'json', path: '/json', name: 'JSON Formatter', shortName: 'JSON', description: 'Format, validate, and inspect JSON documents.', category: 'Formatters', icon: 'json', keywords: ['json', 'validate', 'pretty print', 'api'], loader: () => import('./components/JsonFormatter.vue') },
  { id: 'sql', path: '/sql', name: 'SQL Formatter', shortName: 'SQL', description: 'Make SQL queries clean and readable.', category: 'Formatters', icon: 'sql', keywords: ['sql', 'query', 'database', 'format'], loader: () => import('./components/SqlFormatter.vue') },
  { id: 'csharp', path: '/csharp', name: 'C# Formatter', shortName: 'C#', description: 'Format C# code with consistent indentation.', category: 'Formatters', icon: 'csharp', keywords: ['csharp', 'dotnet', 'code', 'format'], loader: () => import('./components/CSharpFormatter.vue') },
  { id: 'diff', path: '/diff', name: 'Diff Tool', shortName: 'Diff', description: 'Compare two pieces of text side by side.', category: 'Formatters', icon: 'diff', keywords: ['diff', 'compare', 'text', 'changes'], loader: () => import('./components/DiffTool.vue') },
  { id: 'branch', path: '/branch', name: 'Branch Formatter', shortName: 'Branch', description: 'Turn a title into a tidy Git branch name.', category: 'Formatters', icon: 'branch', keywords: ['git', 'branch', 'slug', 'format'], loader: () => import('./components/BranchFormatter.vue') },
  { id: 'container', path: '/container', name: 'Container Generator', shortName: 'Container', description: 'Generate container numbers for testing.', category: 'Generators', icon: 'container', keywords: ['container', 'shipping', 'number', 'generate'], loader: () => import('./components/ContainerGenerator.vue') },
  { id: 'guid', path: '/guid', name: 'GUID Generator', shortName: 'GUID', description: 'Create UUIDs in the format you need.', category: 'Generators', icon: 'guid', keywords: ['guid', 'uuid', 'identifier', 'random'], loader: () => import('./components/GuidGenerator.vue') },
  { id: 'password', path: '/password', name: 'Password Generator', shortName: 'Password', description: 'Create strong, configurable passwords.', category: 'Generators', icon: 'password', keywords: ['password', 'security', 'random', 'secret'], loader: () => import('./components/PasswordGenerator.vue') },
  { id: 'hash', path: '/hash', name: 'Hash Generator', shortName: 'Hash', description: 'Calculate common hashes for text.', category: 'Generators', icon: 'hash', keywords: ['hash', 'sha', 'md5', 'checksum'], loader: () => import('./components/HashGenerator.vue') },
  { id: 'qrcode', path: '/qrcode', name: 'QR Code Generator', shortName: 'QR Code', description: 'Create a QR code from text or a URL.', category: 'Generators', icon: 'qrcode', keywords: ['qr', 'qrcode', 'barcode', 'url'], loader: () => import('./components/QRCodeGenerator.vue') },
  { id: 'cron', path: '/cron', name: 'Cron Generator', shortName: 'Cron', description: 'Build cron expressions with confidence.', category: 'Generators', icon: 'cron', keywords: ['cron', 'schedule', 'expression', 'timer'], loader: () => import('./components/CronGenerator.vue') },
  { id: 'randomnumbers', path: '/randomnumbers', name: 'Random Numbers', shortName: 'Random', description: 'Generate random numbers in a chosen range.', category: 'Generators', icon: 'random', keywords: ['random', 'numbers', 'dice', 'range'], loader: () => import('./components/RandomNumbers.vue') },
  { id: 'timezone', path: '/timezone', name: 'Time Zone Converter', shortName: 'Time Zone', description: 'Convert a time between time zones.', category: 'Converters', icon: 'timezone', keywords: ['time', 'timezone', 'date', 'utc'], loader: () => import('./components/TimeZoneConverter.vue') },
  { id: 'numberbase', path: '/numberbase', name: 'Number Base Converter', shortName: 'Number Base', description: 'Convert decimal, binary, hexadecimal, and more.', category: 'Converters', icon: 'numberbase', keywords: ['binary', 'hex', 'decimal', 'number', 'base'], loader: () => import('./components/NumberBaseConverter.vue') },
  { id: 'unit', path: '/unit', name: 'Unit Converter', shortName: 'Unit', description: 'Convert common measurements quickly.', category: 'Converters', icon: 'unit', keywords: ['unit', 'measurement', 'length', 'weight'], loader: () => import('./components/UnitConverter.vue') },
  { id: 'todo', path: '/todo', name: 'To Do List', shortName: 'To Do', description: 'Keep a lightweight list of focused tasks.', category: 'Productivity', icon: 'todo', keywords: ['todo', 'tasks', 'checklist', 'productivity'], loader: () => import('./components/ToDoList.vue') },
]
export const toolsByCategory = (category: ToolCategory) => tools.filter((tool) => tool.category === category)
export const toolById = (id: unknown) => tools.find((tool) => tool.id === id)
export const filterTools = (query: string) => { const normalized = query.trim().toLowerCase(); return normalized ? tools.filter((tool) => [tool.name, tool.shortName, tool.description, tool.category, ...tool.keywords].join(' ').toLowerCase().includes(normalized)) : tools }
